version: '3'
services:
  vm1:
    build:
      context: .
      dockerfile: Dockerfile
    image: container-ssh:latest
    ports:
      - 5000:22
      - 8080:80
  vm2:
    image: container-ssh:latest
    ports:
      - 5001:22
  vm3:
    build:
      context: .
      dockerfile: DockerfileCentos
    image: container-centos-ssh:latest
    ports:
      - 5002:22
      - 8081:80
