---
- name: Cconfigurando el servicio de SSH
  hosts: vm2
  tasks: 
    - name: Editar configuracion de SSH
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          MaxAuthTries 4
          Banner /etc/motd
          X11Forwarding no
      notify: reiniciar SSH 

  handlers: 
    - name: reiniciar SSH
      service: 
        name: ssh
        state: restarted
