---
- name: Install and start Apache Play
  hosts: httpd
  tasks:
    - name: Install and start Apache
      block:
        - name: install httpd
          apt:
            name: apache2
            state: latest

        - name: Iniciar y habilitar httpd
          service:
            name: apache2
            state: started
            enabled: yes
    - name: La tarea que se expone aqui esta fuera del bloque
      debug:
        msg: "Esto ya esta afuera del bloque"
