---
- name: Working with variables
  hosts: vm1
  vars:
    fav_color: yellow
    port_nums:
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
    users:  #Diccionarios
      bob:
        username: bob
        uid: 1122
        shell: /bin/bash
      lisa:
        username: lisa
        uid: 2233
        shell: /bin/sh
  tasks:
    - name: Show me fav_color value
      debug:
        msg: My favorite color is {{ fav_color }}
    - name: Show me list of ports
      debug:
        msg: Mi lista de puertos {{ port_nums }}
    - name: Show me top of the list
      debug:
        msg: Mi puerto favorito {{ port_nums[0] }}
    - name: Show me top of the list
      debug:
        msg: Uid de Bob {{ users.bob.uid }}